### ISSUE TITLE
Update Documents view frontend to include filtering based on progress

### ISSUE THREAD

**Issue by fionaaac** [CMU-313/fall22-hw3-team-e2#1]
**Effort Required**: Medium time commitment
**Acceptance Criteria**: Admins should be able to filter documents based on their progress
**Dependencies**: None

**Comment by phi-h-nguyen** [comment]
![Image](https://user-images.githubusercontent.com/57329141/193969837-a87c929a-5c2d-413d-b5d9-792262c8b66c.png)
